import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "sonner";
import QueryProvider from "@/components/query-provider";

export const metadata: Metadata = {
    title: "TicTacToe",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <QueryProvider>{children} </QueryProvider>
            </body>
            <Toaster />
        </html>
    );
}
