import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "sonner";
import QueryProvider from "@/components/query-provider";
import { SocketProvider } from "@/components/SocketProvider";

export const metadata: Metadata = {
    title: "TicTacToe",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <head />
            <body>
                <QueryProvider>
                    <SocketProvider>
                        {children}
                        <Toaster />
                    </SocketProvider>
                </QueryProvider>
            </body>
        </html>
    );
}
