# Use a lightweight Node.js image
FROM node:20-alpine

# Set the working directory inside the container
WORKDIR /server

# Copy package.json and package-lock.json to install dependencies
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the server files into the container
COPY . .

# Expose the port your WebSocket server will run on
EXPOSE 3001

# Start the WebSocket server
CMD ["node", "websocketServer.js"]
